name: Transfer Secrets
on: workflow_dispatch

jobs:
  copy-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Transfer
        env:
          GH_TOKEN: ${{ secrets.TRANSFER_TOKEN }}
          DEST_REPO: "operacoesicaiu/icaiu-data"
          ZENVIA_ACCESS_TOKEN: ${{ secrets.ZENVIA_ACCESS_TOKEN }}
          ZENVIA_QUEUE_ID: ${{ secrets.ZENVIA_QUEUE_ID }}
        run: |
          gh secret set ZENVIA_ACCESS_TOKEN --repo "$DEST_REPO" --body "$ZENVIA_ACCESS_TOKEN"
          gh secret set ZENVIA_QUEUE_ID --repo "$DEST_REPO" --body "$ZENVIA_QUEUE_ID"
